config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    get 'users/login', to: 'users/sessions#new', as: :new_user_session
    get 'users/logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root 'application#index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :users do
    collection do
      get 'search'
    end
  end

  resources :activities do
    member do
      get :delete
      post :verify_attendance
      get :signups
      post :signup
    end
  end

  # config/routes.rb
  resources :activity_types do
    member do
      get :delete
    end
  end

  resources :articles do
    member do
      get :delete
    end
  
    collection do
      get :recent_articles
    end
  end
  

  resources :article_categories do
    member do
      get :delete
    end
  end
  resources :article_modules do
    member do
      get :delete
      post :increase_priority
      post :decrease_priority
    end
  end

  get 'advanced_settings/index'
  get 'help', to: 'general#help'

  root 'welcome#index'
end

app/models/article_module.rb
class ArticleModule < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  validates :name, presence: true
end

app/controllers/article_modules_controller.rb
class ArticleModulesController < ApplicationController
    before_action :set_module, only: %i[edit update destroy delete show increase_priority decrease_priority]

    def index
      @article_modules = ArticleModule.order(priority: :asc)
      authorize @article_modules
    end

    def new
      @article_module = ArticleModule.new
      authorize @article_module
    end

    def edit
      authorize @article_module
    end

    def delete
      authorize @article_module
    end

    def create
      @article_module = ArticleModule.new(article_module_params)
      authorize @article_module

      @article_module.priority = ArticleModule.maximum(:priority).to_i + 1

      respond_to do |format|
        if @article_module.save
          format.html { redirect_to article_modules_url, notice: "Article module was successfully created." }
          format.json { render :show, status: :created, location: @article_module }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @article_module.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize @article_module
      respond_to do |format|
        if @article_module.update(article_module_params)
          format.html { redirect_to article_modules_url, notice: "Article module was successfully updated." }
          format.json { render :show, status: :ok, location: @article_module }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article_module.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @article_module
      @article_module.destroy
      respond_to do |format|
        format.html { redirect_to article_modules_url, notice: "Article module was successfully deleted." }
        format.json { head :no_content }
      end
    end

    def increase_priority
      authorize @article_module, :update?
      @article_module_above = ArticleModule.where("priority < ?", @article_module.priority).order(priority: :desc).first

      if @article_module_above
        @article_module_above.update(priority: @article_module.priority)
        @article_module.update(priority: @article_module.priority - 1)
      end

      flash[:notice] = "Priority updated"
      redirect_to article_modules_url
    end

    def decrease_priority
      authorize @article_module, :update?
      @article_module_below = ArticleModule.where("priority > ?", @article_module.priority).order(priority: :asc).first

      if @article_module_below
        @article_module_below.update(priority: @article_module.priority)
        @article_module.update(priority: @article_module.priority + 1)
      end

      flash[:notice] = "Priority updated"
      redirect_to article_modules_url
    end

    private

    def set_module
      @article_module = ArticleModule.find(params[:id])
    end

    def article_module_params
        params.require(:article_module).permit(:name)
    end
end

app/views/article_modules/_article_module.html.erb
<div>
  <p><%= article_module.name %></p>
</div>

app/views/article_modules/_form.html.erb
<%= form_with(model: @article_module) do |form| %>
  <div class="row">
    <div class="d-flex flex-column">
      <div class="form-floating mb-3">
        <%= form.text_field :name, class: "form-control", id: "floatingName", placeholder: "Name" %>
        <%= form.label :name, for: "floatingName" %>
      </div>

      <div>
        <%= form.submit class: "btn btn-primary mt-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/article_modules/delete.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: "Modules", path: article_modules_path },
  { name: @article_module.name, path: article_modules_path },
  { name: "Delete" }
]) %>

<div>
  <h2>Delete Article Module</h2>
  <p>Are you sure you want to permanently delete <strong><%= @article_module.name %></strong>?</p>
  <p>This will delete ALL the articles associated with the module!</p>
  <%= button_to "Delete Module", article_module_path(@article_module), method: :delete, class: "btn btn-danger" %>
</div>

app/views/article_modules/edit.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: "Modules", path: article_modules_path },
  { name: @article_module.name, path: article_modules_path },
  { name: "Edit" }
]) %>

<h1>Edit Module</h1>

<%= render "form", article_module: @article_module %>

app/views/article_modules/index.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: "Modules" },
]) %>

<div class="hstack mb-3">
  <h1>Modules</h1>
  <div class="ms-auto">
    <%= link_to 'New Module', new_article_module_path, class: "btn btn-primary" %>
  </div>
</div>

<div>
  <div class="hstack">
    <div class="vstack gap-3">
      <div class="card">
        <ul class="list-group list-group-flush">
          <% @article_modules.each do |article_module| %>
            <li class="list-group-item hstack gap-2">
              <%= button_to increase_priority_article_module_path(article_module), method: :post,
                            class: 'btn btn-sm btn-outline-secondary', data: { cta_id: "#{article_module.id}_inc" } do %>
                <span class="fas fa-arrow-up"></span>
              <% end %>
              <%= button_to decrease_priority_article_module_path(article_module), method: :post,
                            class: 'btn btn-sm btn-outline-secondary', data: { cta_id: "#{article_module.id}_dec" } do %>
                <span class="fas fa-arrow-down"></span>
              <% end %>
              <%= article_module.name %>
              <div class="ms-auto hstack gap-2">
                <%= link_to 'Edit', edit_article_module_path(article_module), class: "btn btn-secondary" %>
                <%= link_to 'Delete', delete_article_module_path(article_module), class: "btn btn-danger" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/article_modules/new.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: "Modules", path: article_modules_path },
  { name: "New" }
]) %>

<h1>New Module</h1>

<%= render "form" %>