config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    get 'users/login', to: 'users/sessions#new', as: :new_user_session
    get 'users/logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root 'application#index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :users do
    collection do
      get 'search'
    end
  end

  resources :activities do
    member do
      get :delete
      post :verify_attendance
      get :signups
      post :signup
    end
  end

  # config/routes.rb
  resources :activity_types do
    member do
      get :delete
    end
  end

  resources :articles do
    member do
      get :delete
    end
  
    collection do
      get :recent_articles
    end
  end
  

  resources :article_categories do
    member do
      get :delete
    end
  end
  resources :article_modules do
    member do
      get :delete
      post :increase_priority
      post :decrease_priority
    end
  end

  get 'advanced_settings/index'
  get 'help', to: 'general#help'

  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :article_category
  belongs_to :article_module

  validates :title, presence: true
  validates :body, presence: true
  validates :article_category_id, presence: true
  validates :article_module_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: %i[edit update destroy delete show]

    def index
      filtered_categories = params[:category]
      searched_articles = params[:search]

      if filtered_categories.present?
        @articles = Article.where(article_category_id: filtered_categories)
      elsif searched_articles.present?
        @articles = Article.where("title ILIKE ? OR body ILIKE ?", "%#{searched_articles}%", "%#{searched_articles}%")
      else
        @articles = Article.all
      end

      @articles = @articles.joins(:article_module).order('article_modules.priority ASC').group_by(&:article_module)

      @modules = ArticleModule.all.order(priority: :asc)
      @categories = ArticleCategory.all
    end

    def show
    end

    def new
      @article = Article.new
      authorize @article
    end

    def edit
      authorize @article
    end

    def delete
      authorize @article
    end

    def create
      @article = Article.new(article_params)
      authorize @article

      respond_to do |format|
        if @article.save
          format.html { redirect_to articles_url, notice: "Article was successfully created." }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @article.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize @article

      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: "Article was successfully updated." }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @article

      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: "Article was successfully deleted." }
        format.json { head :no_content }
      end
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :body, :article_module_id, :article_category_id)
    end
end

app/views/articles/_article.html.erb
<div class="hstack mb-3">
  <div class="vstack">
    <div class="display-6">
      <%= article.title %>
    </div>
    <%= article.article_module.name %>
    <span>
      <span class="badge rounded-pill text-bg-secondary"><%= article.article_category.name %></span>
    </span>
  </div>
  <div class="ms-auto hstack gap-2 flex-wrap justify-content-end">
    <%= link_to "Edit", edit_article_path(article), class: "btn btn-primary" %>
    <%= link_to "Delete", delete_article_path(article), class: "btn btn-danger" %>
  </div>
</div>

<div class="tiptap card">
  <div class="card-body mt-3">
    <%= article.body.html_safe %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
  <div class="row">
    <div class="d-flex flex-column">
      <div class="form-floating mb-3">
        <%= form.text_field :title, class: "form-control", id: "floatingTitle", placeholder: "Title" %>
        <%= form.label :title, for: "floatingTitle" %>
      </div>

      <div class="form-floating mb-3">
        <%= form.collection_select :article_category_id, ArticleCategory.all, :id, :name, { prompt: "Select Category" }, { class: "form-select", id: "floatingCategory" } %>
        <%= form.label :category_id, for: "floatingCategory" %>
      </div>

      <div class="form-floating mb-3">
        <%= form.collection_select :article_module_id, ArticleModule.order(:priority), :id, :name, { prompt: "Select Module" }, { class: "form-select", id: "floatingModule" } %>
        <%= form.label :module_id, for: "floatingModule" %>
      </div>

      <label class="form-label">Body</label>
      <%= render partial: 'layouts/shared/editor', locals: { form: form, field_name: :body } %>

      <div>
        <%= form.submit class: "btn btn-primary mt-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/delete.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: @article.title, path: article_path(@article) },
  { name: "Delete" }
]) %>

<div>
  <h2>Delete Activity</h2>
  <p>Are you sure you want to permanently delete <strong><%= @article.title %></strong>?</p>
  <%= button_to "Delete Article", article_path(@article), method: :delete, class: "btn btn-danger" %>
</div>

app/views/articles/edit.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: @article.title, path: article_path(@article) },
  { name: "Edit" }
]) %>

<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="hstack mb-3">
  <h1>Articles</h1>
  <% if current_user.officer? %>
    <div class="ms-auto hstack gap-2 flex-wrap justify-content-end">
      <%= link_to 'Modules', article_modules_path, class: "btn btn-outline-secondary" %>
      <%= link_to 'Categories', article_categories_path, class: "btn btn-outline-secondary" %>
      <%= link_to 'New Article', new_article_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<div>
  <div class="hstack gap-3 flex-wrap-reverse align-items-end">
    <div class="vstack gap-3 col col-8-md">
      <%= form_with url: articles_path, method: :get do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search articles..." %>
          <%= submit_tag 'Search', class: "btn btn-primary" %>
        </div>
      <% end %>
      <% if @articles.empty? %>
        <p>No articles were found.</p>
      <% else %>
        <% @articles.each do |article_module, articles| %>
          <div class="card">
            <div class="card-header fw-light p-3 fs-4">
              <%= article_module.name %>
            </div>
            <ul class="list-group list-group-flush">
              <% articles.each do |article| %>
                <%= link_to article, class: 'list-group-item list-group-item-action p-3 hstack gap-2' do %>
                  <%= article.title %>
                  <div class="ms-auto">
                    <span class="badge rounded-pill text-bg-secondary"><%= article.article_category.name %></span>
                  </div>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col col-4-md">
      <div class="card">
        <div class="card-header">
          Categories
        </div>
        <div class="card-body">
          <%= form_with url: articles_path, method: :get do %>
            <% @categories.each do |category| %>
              <div class="form-check">
                <%= check_box_tag 'category[]', category.id, params[:category].blank? || params[:category]&.include?(category.id.to_s), id: "category_#{category.id}", class: "form-check-input" %>
                <%= label_tag "category_#{category.id}", category.name, class: "form-check-label" %>
              </div>
            <% end %>
            <%= submit_tag 'Filter', class: "btn btn-primary mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: "New" }
]) %>

<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Articles", path: articles_path },
  { name: @article.title },
]) %>

<%= render @article %>