config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    get 'users/login', to: 'users/sessions#new', as: :new_user_session
    get 'users/logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root 'application#index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :users do
    collection do
      get 'search'
    end
  end

  resources :activities do
    member do
      get :delete
      post :verify_attendance
      get :signups
      post :signup
    end
  end

  # config/routes.rb
  resources :activity_types do
    member do
      get :delete
    end
  end

  resources :articles do
    member do
      get :delete
    end
  
    collection do
      get :recent_articles
    end
  end
  

  resources :article_categories do
    member do
      get :delete
    end
  end
  resources :article_modules do
    member do
      get :delete
      post :increase_priority
      post :decrease_priority
    end
  end

  get 'advanced_settings/index'
  get 'help', to: 'general#help'

  root 'welcome#index'
end

app/controllers/activity_types_controller.rb
# app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
    before_action :set_activity_type, only: %i[show edit update destroy delete]
  
    def index
      @activity_types = ActivityType.all
    end
  
    def show
    end

    def delete
    end
  
    def new
      @activity_type = ActivityType.new
    end
  
   # app/controllers/activity_types_controller.rb
   def create
    @activity_type = ActivityType.new(activity_type_params)
  
    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to activity_types_url, notice: "Activity type was successfully created." }
        format.json { render :show, status: :created, location: @activity_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity_type.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
  

  
    def edit
    end
  
    # app/controllers/activity_types_controller.rb

    def update
      respond_to do |format|
        if @activity_type.update(activity_type_params)
          format.html { redirect_to activity_types_url, notice: "Activity type was successfully updated." }
          format.json { render :show, status: :ok, location: @activity_type }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

  
    def destroy
      @activity_type.destroy
    
      respond_to do |format|
        format.html { redirect_to activity_types_url, notice: 'Activity type was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
  
    private
  
    def set_activity_type
      @activity_type = ActivityType.find(params[:id])
    end
  
    def activity_type_params
      params.require(:activity_type).permit(:title)
    end
end

app/views/activity_types/_activity_type.html.erb
<h1>Activity Type Details</h1>
<p><strong>Title:</strong> <%= @activity_type.title %></p>

app/views/activity_types/_form.html.erb
<!-- app/views/activity_types/_form.html.erb -->
<%= form_with(model: activity_type) do |form| %>
  <% if @activity_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@activity_type.errors.count, "error") %> prohibited this activity type from being saved:</h2>

      <ul>
        <% @activity_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activity_types/delete.html.erb
<h2>Delete Activity Type</h2>

  <%= form_for(@activity_type, method: 'delete') do |f| %>
    <% # url: task_path(@activity_type), method: 'delete' %>

    <p>Are you sure you want to permanently delete this activity type?</p>
    <%= render @activity_type %>

    <div class="form-buttons">
      <%= button_to("Delete Activity Type", @activity_type, method: :delete, class: "btn btn-danger") %>
    </div>

  <% end %>

app/views/activity_types/edit.html.erb
<h1>Edit Activity Type</h1>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Activity Types</h1>

<ul>
  <% @activity_types.each do |activity_type| %>
    <li><%= activity_type.title %></li>
    <%= link_to 'Edit Activity Type', edit_activity_type_path(activity_type) %>
    <%= link_to "Delete", delete_activity_type_path(activity_type)%>
  <% end %>
</ul>

<%= link_to 'New Activity Type', new_activity_type_path %><br>
<%= link_to 'Back', advanced_settings_index_path %>

app/views/activity_types/new.html.erb
<h1>New Activity Type</h1>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/show.html.erb
<%= render @activity_type %>
<%= link_to 'Back', activity_types_path %>