config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks'
             }
  devise_scope :user do
    get 'users/login', to: 'users/sessions#new', as: :new_user_session
    get 'users/logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root 'application#index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :users do
    collection do
      get 'search'
    end
  end

  resources :activities do
    member do
      get :delete
      post :verify_attendance
      get :signups
      post :signup
    end
  end

  # config/routes.rb
  resources :activity_types do
    member do
      get :delete
    end
  end

  resources :articles do
    member do
      get :delete
    end
  
    collection do
      get :recent_articles
    end
  end
  

  resources :article_categories do
    member do
      get :delete
    end
  end
  resources :article_modules do
    member do
      get :delete
      post :increase_priority
      post :decrease_priority
    end
  end

  get 'advanced_settings/index'
  get 'help', to: 'general#help'

  root 'welcome#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_participations, dependent: :destroy
  belongs_to :activity_type
  validates :activity_type, presence:true
  validates :title, presence:true
  validates :description, presence:true
  validates :start_time, presence:true
  validates :end_time, presence:true
  validates :passcode, presence:true

  enum status: { scheduled: 0, postponed: 1, canceled: 2 }
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
    has_many :activities
    validates :title, presence:true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :set_activity, only: %i[edit update destroy delete]
    before_action :set_activity_and_signup, only: %i[show signup verify_attendance]
    helper_method :status_class, :show_verify_attendance_button, :show_signup_button

    def index
      @activities = Activity.order(:start_time)
      @upcoming_activities = @activities.where('start_time >= ?', Time.zone.now).where('start_time <= ?', Time.zone.now + 7.days)

      if params[:view].present?
        session[:view] = params[:view]
      else
        session[:view] ||= 'calendar'
      end

      @preferred_view = session[:view]
    end

    def show
      @first_five_signups = @activity.activity_participations.limit(5)
      @num_signups = @activity.activity_participations.count
    end

    def new
      @activity = Activity.new
      authorize @activity
      if @activity.passcode.nil?
        @activity.passcode = SecureRandom.random_number(1_000_000)
      end
    end

    def edit
      authorize @activity
    end

    def delete
      authorize @activity
    end

    def signups
      @activity = Activity.find(params[:id])
      @signups = @activity.activity_participations
    end

    def create
      # Check if the selected activity_type_id exists
      activity_type_id = params[:activity][:id].to_i
      activity_type = ActivityType.find_by(id: activity_type_id)

      # Create a new ActivityType if it doesn't exist
      activity_type ||= ActivityType.find_or_create_by(title: "Meeting")

      # Create a new Activity
      @activity = Activity.new(activity_params.merge(activity_type_id: activity_type.id))
      authorize @activity

      respond_to do |format|
        if @activity.save
          flash[:notice] = "Activity was successfully created."
          format.html { redirect_to activities_url }
          format.json { render :show, status: :created, location: @activity }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @activity.errors, status: :unprocessable_entity }
        end
      end
    end


    def update
      authorize @activity
      respond_to do |format|
        if @activity.update(activity_params)
          flash[:notice] = "Activity was successfully updated."
          format.html { redirect_to activities_url }
          format.json { render :show, status: :ok, location: @activity }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @activity.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @activity
      @activity.destroy

      respond_to do |format|
        flash[:notice] = "Activity was successfully deleted."
        format.html { redirect_to activities_url }
        format.json { head :no_content }
      end
    end

    def signup
      respond_to do |format|
        if @signup.present? && @signup.persisted?
          @signup.update(signup_params)
          flash[:notice] = "Sign up status was successfully updated."
          format.html { redirect_to activity_url(@activity) }
        else
          @signup = ActivityParticipation.new(signup_params.merge(user: current_user, activity: @activity))
          @signup.save
          flash[:notice] = "You have successfully signed up for this activity."
          format.html { redirect_to activity_url(@activity) }
        end
      end
    end

    def verify_attendance
      respond_to do |format|
        if @activity.passcode.to_s == params[:passcode_input].to_s
          current_time = Time.now
          if current_time >= @activity.start_time && current_time <= @activity.end_time
            activity_participation = ActivityParticipation.find_or_initialize_by(
              user: current_user,
              activity: @activity
            )
            if activity_participation.persisted?
              # If the record already exists, update attended and status
              activity_participation.update(attended: true, status: ActivityParticipation.statuses[:going])
            else
              # If the record doesn't exist, create a new one with attended and status
              activity_participation.attended = true
              activity_participation.status = ActivityParticipation.statuses[:going]
              activity_participation.save
            end
            flash[:notice] = "Passcode is correct"
            format.html { redirect_to activity_url(@activity) }
          else
            flash[:notice] = "Passcode is no longer valid"
            flash[:error] = true
            format.html { redirect_to activity_url(@activity) }
          end
        else
          flash[:notice] = "Passcode is incorrect"
          flash[:error] = true
          format.html { redirect_to activity_url(@activity) }
        end
      end

    end

    def status_class
      return 'text-bg-success' if @activity.scheduled?
      return 'text-bg-warning' if @activity.postponed?
      'text-bg-danger' if @activity.canceled?
    end

    def show_verify_attendance_button
      return false if @signup.attended?
      return false if @activity.start_time > Time.now
      return false if @activity.end_time < Time.now
      return false if @activity.postponed? || @activity.canceled?
      true
    end

    def show_signup_button
      return false if @signup.attended?
      true
    end

    private

    def set_activity
      @activity = Activity.find(params[:id])
    end

    def set_activity_and_signup
      @activity = Activity.find(params[:id])
      @signup = ActivityParticipation.find_or_initialize_by(user: current_user, activity: @activity)
    end

    def activity_params
      params.require(:activity).permit(:activity_type_id, :title, :description, :start_time, :end_time, :status, :location, :passcode, :points)
    end

    def signup_params
      params.require(:activity_participation).permit(:status)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def view_button(view_type, current_view)
    active_class = view_type == current_view ? 'active' : ''
    icon = view_type == 'list' ? 'fa fa-list' : 'fa-regular fa-calendar'
    view_name = view_type.capitalize + ' View'

    link_to activities_path(view: view_type), class: "btn btn-secondary #{active_class}" do
      "<i class='#{icon}'></i> #{view_name}".html_safe
    end
  end
end

app/views/activities/_activity.html.erb
<div class="row g-4 mb-4">
  <div class="col-xl-8">
    <div class="mb-4 d-flex align-items-center">
      <div>
        <div class="display-6">
          <%= activity.title %>
        </div>
        <span class="badge rounded-pill <%= status_class %>">
          <%= activity.status.humanize %>
        </span>
        <span class="badge rounded-pill text-bg-primary">
          <%= activity.activity_type.title %>
        </span>
      </div>
      <% if current_user.officer? %>
        <div class="ms-auto">
          <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-primary" %>
          <%= link_to 'Delete', delete_activity_path(activity), class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>

    <div class="border-top border-bottom pt-3 pb-3 d-flex align-items-center">
      <% if @signup.status.present? %>
        <span>
          <strong>Your Status: </strong> <%= @signup.status_or_attended %>
        </span>
      <% end %>
      <div class="hstack gap-2 ms-auto">
        <% if show_signup_button %>
          <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#signupModal">
            <% if @signup.status.present? %>
              Change Status
            <% else %>
              Sign Up
            <% end %>
          </button>
        <% end %>
        <% if show_verify_attendance_button %>
          <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#attendanceModal">
            Verify Attendance
          </button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-xl-4">
    <div class="card h-100 shadow-sm">
      <div class="card-body">
        <h5 class="card-title">Activity Details</h5>
        <p>
          <i class="fa-solid fa-location-dot text-secondary me-2"></i><%= activity.location %>
        </p>
        <p class="m-0 p-0">
          <strong>Start: </strong>
          <%= I18n.l(activity.start_time, format: :long) %>
        </p>
        <p class="m-0 p-0">
          <strong>End: </strong>
          <%= I18n.l(activity.end_time, format: :long) %>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row g-4">
  <div class="col-xl-8 tiptap card">
    <div class="card-body mt-3">
      <%= activity.description.html_safe %>
    </div>
  </div>
  <div class="col-xl-4">
    <ul class="list-group">
      <% @first_five_signups.each do |signup| %>
        <li class="list-group-item">
          <div class="hstack gap-3">
            <img src="<%= signup.user.profile_picture %>" class="rounded-circle" width="30" height="30">
            <span>
              <strong><%= signup.user.first_name %> <%= signup.user.last_name %></strong> <%= signup.third_person_status.downcase %>
            </span>
            <% if signup.attended %>
              <i class="fa-solid fa-check text-success ms-auto"></i>
            <% end %>
          </div>
        </li>
      <% end %>
      <li class="list-group-item d-grid">
          <%= link_to signups_activity_path(activity), class: "link link-secondary link-underline-opacity-0 pt-1 pb-1" do %>
            <div class="hstack gap-3">
              <span>
                See All Signups
              </span>
              <i class="fa-solid fa-arrow-right ms-auto"></i>
            </div>
          <% end %>
      </li>
    </ul>
    <div class="text-secondary text-end fs-6 fw-light mt-3">
      <i class="fa-solid fa-user-friends me-2"></i><%= pluralize(@num_signups, 'Member') %> Signed Up
    </div>
  </div>
</div>

<%= form_with(model: activity, url: verify_attendance_activity_path(activity), method: :post) do |form| %>
  <div class="modal fade" id="attendanceModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Verify Attendance</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="mb-3">
              <%= label_tag :passcode_input, "Passcode", class: "form-label" %>
              <%= number_field_tag :passcode_input, nil, class: "form-control" %>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit "Submit Passcode", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= form_with(model: @signup, url: signup_activity_path(activity), method: :post) do |form| %>
  <div class="modal fade" id="signupModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Sign Up for Activity</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3">
            <%= form.label :status %>
            <%= form.select :status, ActivityParticipation.statuses.keys.map { |status| [status.humanize, status] }, {}, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit "Submit", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/_form.html.erb
<%= form_with(model: @activity) do |form| %>
  <div class="row">
    <div class="d-flex flex-column">
      <div class="form-floating mb-3">
        <%= form.text_field :title, class: "form-control", id: "floatingTitle", placeholder: "Title" %>
        <%= form.label :title, for: "floatingTitle" %>
      </div>

      <label class="form-label">Description</label>
      <%= render partial: 'layouts/shared/editor', locals: { form: form, field_name: :description } %>

      <label class="form-label">Meeting Details</label>

      <div class="form-floating mb-3">
        <%= form.collection_select :activity_type_id, ActivityType.all, :id, :title, { prompt: 'Select or create an activity type' }, class: "form-select", id: "floatingActivityType" %>
        <%= form.label :activity_type_id, 'Activity Type', for: "floatingActivityType" %>
      </div>

      <div class="row g-2 mb-3">
        <div class="form-floating col-md">
          <%= form.datetime_local_field :start_time, class: "form-control", id: "floatingStartTime" %>
          <%= form.label :start_time, 'Start Time', for: "floatingStartTime" %>
        </div>

        <div class="form-floating col-md">
          <%= form.datetime_local_field :end_time, class: "form-control", id: "floatingEndTime" %>
          <%= form.label :end_time, 'End Time', for: "floatingEndTime" %>
        </div>
      </div>

      <div class="form-floating mb-3">
        <%= form.text_field :location, class: "form-control", id: "floatingLocation", placeholder: "Location" %>
        <%= form.label :location, for: "floatingLocation" %>
      </div>

      <div class="form-floating mb-3">
        <%= form.number_field :passcode, class: "form-control", id: "floatingPasscode", placeholder: "Passcode" %>
        <%= form.label :passcode, for: "floatingPasscode" %>
      </div>

      <div class="form-floating mb-3">
        <%= form.number_field :points, class: "form-control", id: "floatingPoints", placeholder: "Points" %>
        <%= form.label :points, for: "floatingPoints" %>
      </div>

      <div class="form-floating mb-3">
        <%= form.select :status, Activity.statuses.keys.map { |status| [status.humanize, status] }, {}, class: "form-control", id: "floatingStatus" %>
        <%= form.label :status, for: "floatingStatus" %>
      </div>

      <div>
        <%= form.submit class: "btn btn-primary mt-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/delete.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Activities", path: activities_path },
  { name: @activity.title, path: activity_path(@activity) },
  { name: "Delete" }
]) %>

<div>
  <h2>Delete Activity</h2>
  <p>Are you sure you want to permanently delete <strong><%= @activity.title %></strong>?</p>
  <%= button_to "Delete Activity", activity_path(@activity), method: :delete, class: "btn btn-danger" %>
</div>

app/views/activities/edit.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Activities", path: activities_path },
  { name: @activity.title, path: activity_path(@activity) },
  { name: "Edit" }
]) %>

<h1>Edit Activity</h1>
<%= render "form", activities: @activity %>

app/views/activities/index.html.erb
<div class="d-flex align-items-center mb-3">
  <h1>All Activities</h1>

  <div class="btn-group btn-group-toggle ms-auto" data-toggle="buttons">
    <%= view_button('calendar', session[:view]) %>
    <%= view_button('list', session[:view]) %>
  </div>

  <% if current_user.officer? %>
    <%= link_to 'New Activity', new_activity_path, class: "ms-3 btn btn-primary" %>
  <% end %>
</div>

<% if @preferred_view == "calendar" %>
  <div id="calendar" class="card p-4 shadow-sm">
    <%= render SimpleCalendar::MonthCalendar.new(self, events: @activities) do |date, activities| %>
      <div class="fw-light mb-2">
        <%= date.day %>
      </div>

      <div class="d-flex flex-column gap-1">
        <% activities.each do |activity| %>
          <div data-bs-toggle="tooltip" data-bs-placement="top"
               data-bs-title="<%= I18n.l(activity.start_time, format: :short) %>">
            <%= link_to activity, class: "event d-flex align-items-center gap-2 ps-2 pe-2 badge fw-light text-wrap" do %>
              <i class="fa-regular fa-calendar-days"></i> <%= activity.title %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

    <p class="fw-light text-secondary text-end badge">Activities shown in the <%= Time.zone %> timezone</p>
  </div>
<% else %>
  <ul class="list-group">
    <% @activities.each do |activity| %>
      <%= link_to activity, class: "list-group-item list-group-item-action pt-2 pb-2" do %>
        <div class="d-flex align-items-center">
          <div class="d-flex flex-column">
            <span class="h5 fw-bold m-0"><%= activity.title %></span>
            <span class="fw-light m-0"><%= l(activity.start_time, format: :short) %></span>
          </div>
          <div class="ms-auto">
            <span class="me-2">View Activity</span>
            <i class="fa-solid fa-arrow-right ms-auto"></i>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/activities/new.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Activities", path: activities_path },
  { name: "New" }
]) %>

<h1>New Activity</h1>

<%= render "form", activities: @activity %>

<br>

<div>
  <%= link_to 'Advanced Settings', advanced_settings_index_path %>
</div>

app/views/activities/show.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Activities", path: activities_path },
  { name: @activity.title }
]) %>

<%= render @activity %>

app/views/activities/signups.html.erb
<%= render("layouts/shared/breadcrumb", breadcrumbs: [
  { name: "Activities", path: activities_path },
  { name: @activity.title, path: activity_path(@activity) },
  { name: "Signups" }
]) %>

<ul class="list-group">
  <% @signups.each do |signup| %>
    <%= link_to user_path(signup.user), class: "list-group-item list-group-item-action pt-2 pb-2" do %>
      <div class="hstack gap-3 fs-5">
        <img src="<%= signup.user.profile_picture %>" class="rounded-circle" width="40" height="40">
        <span>
          <strong><%= signup.user.first_name %> <%= signup.user.last_name %></strong> <%= signup.third_person_status.downcase %>
        </span>
        <% if signup.attended %>
          <i class="fa-solid fa-check text-success ms-auto"></i>
        <% end %>
      </div>
    <% end %>
  <% end %>
</ul>